routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/tes', function () {
    return view('layouts.tes');
});

Route::get('/api/products',function(){
	return App\Product::where('name','LIKE','%'.request('q').'%')->paginate(10);
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::middleware(['auth'])->group(function (){

    Route::get('autocomplete', 'ProductsController@autocomplete')->name('autocomplete');
    Route::resource('customers', 'CustomersController');
    Route::resource('products', 'ProductsController');
    Route::resource('reports', 'ReportController');
    Route::resource('transactions', 'TransactionsController');
    Route::resource('costs', 'ProductionCostsController');
    Route::resource('units', 'UnitProductsController');

    Route::get('/findPrice','TransactionsController@findPrice');

    Route::get('/transactionData','ProductionCostsController@transactionData');
    Route::get('/unitPrice','ProductionCostsController@unitPrice');

    Route::get('invoice','TransactionsController@invoice');
    Route::post('/transactions/postInvoice','TransactionsController@postInvoice');
});











Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/TransactionsController.php
<?php

namespace App\Http\Controllers;

use App\Transaction;
use App\Product;
use App\Customer;
use App\ProductionCost;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;


class TransactionsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // $transaction = 4;
        // $costs = ProductionCost::where('order_id',$transaction)->get();
        // dd($costs);
        // dd(Auth::user()->id);
        $transactions = Transaction::all();
        // dd($transactions);
        return view('transactions.index',['transactions'=> $transactions]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $rand = str_random(8);
        $invoice = 'SF'.$rand;
        $products = Product::all();
        $customers = Customer::all();

        // dd($customers);
        return view('transactions.create',['invoices'=>$invoice, 'customers'=>$customers, 'products'=>$products]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // $biaya = $request->input('bayar');
        $user= Auth::user()->id;
        $status="Dalam Proses";

        // $number = count($_POST["productname"]);
        // dd($number);
        $transactions = Transaction::create([
            'invoice_no' => $request->input('no_invoice'),
            'order_name' => $request->input('order_name'),
            'user_id' => $user,
            'customer_id' => $request->input('customer'),
            'total_order' => $request->input('biaya_total'),
            'payment' => $request->input('bayar'),
            'kurang' => $request->input('kurang'),
            'notes' => $request->input('notes'),
            'status' => $status,
            'tanggal_jadi' => $request->input('tanggal_jadi')
        ]);

        $transaction = Transaction::orderBy('created_at', 'desc')->first();
        $id_transaction = $transaction-> id;

        $forProduct= Transaction::findOrFail($id_transaction);
        // dd($transaction);
        // if($number > 0)  
        // {  
        //     for($i=0; $i<$number; $i++)  
        //     { 
        //         $products=$forProduct->Products()->attach($_POST['product_name'][$i],['quantity'=>$_POST['quantity'][$i],'jumlah_harga'=>$_POST['jumlah_harga'][$i]]);
        //     }
        // }
        
        for ($i = 1; $i <= count($request->productname); $i++) {
            if (!empty($request->productname[$i])) {
            $products=$forProduct->Products()->attach($request->productname[$i],['quantity'=>$request->quantity[$i],'jumlah_harga'=>$request->jumlah_harga[$i]]);
            }
        }

        // return redirect() -> route('transactions.index');
        // return redirect('transactions')->with('success', 'Your order successfully submitted');
        if($transactions){
            return redirect() -> route('transactions.show', $id_transaction)
            -> with('success', 'Product created successfully');
        }
        return back() -> withInput() -> with('errors','operation failed');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Transaction  $transaction
     * @return \Illuminate\Http\Response
     */
    public function show($transaction)
    {
        $transactions = Transaction::findorfail($transaction);
        // $detail = $transactions-> DetailOrder;
        $customer = $transactions-> Customer;
        $user = $transactions-> User;
        // $product = Product::findorfail($detail);

        // $products = DetailOrder::find(1);
        // $product = $transactions->Products()->attach(1,['quantity'=>4,'jumlah_harga'=>220000]);
        $product = $transactions-> Products;
        // $unit = $transactions-> Products->first()-> UnitProduct;


        
        // foreach ($transactions->Products as $product) {
        //    echo $product->pivot->quantity;
          
        //    echo $product->pivot->jumlah_harga;

        // }
        // dd($products);
        return view('transactions.show',['transactions'=>$transactions,'customers'=>$customer, 'users'=>$user, 'products'=>$product]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Transaction  $transaction
     * @return \Illuminate\Http\Response
     */
    public function edit(Transaction $transaction)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Transaction  $transaction
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $transaction)
    {        

        $costs = ProductionCost::where('order_id',$transaction)->get();
        // dd($costs);

        if ($costs->isNotEmpty()) {
            $itemUpdate = Transaction::where('id',$transaction)
            ->update([
            'status' => $request->input('status')
            ]);
        } else {
            $message = "belum belanja";
            echo "<script type='text/javascript'>alert('$message');</script>";
            // return back()->withInput();
            return redirect()->route('transactions.index')->with('error','belum belanja');
        }
       
        if ($itemUpdate) {
            return redirect()->route('transactions.index')
            ->with('success', 'Order diambil Successfully');
        }
        
        return back()->withInput()->with('error','belum belanja');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Transaction  $transaction
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request)
    {
        $deleteItem = Transaction::find($request-> order_id);
        $deleteProduk= $deleteItem->Products()->detach();
        // dd($deleteItem);
        if ($deleteItem->delete()) {
            
            return redirect()->route('transactions.index')
            ->with('success', 'Transaction deleted successfully');
        }

        return back()->withInput()->with('error','operation failed');
    }

    public function findPrice(Request $request)
    {

     $p = Product::select('price')->where('id',$request->id)->first();
    //  dd($p);
     return response()->json($p);

    }

    public function invoice(){
        return view('transactions.invoice');
    }
}

resources/views/transactions/edit.blade.php
@extends('layouts.root')

@section('content')

<div class="page-breadcrumb">
    <div class="row">
        <div class="col-12 d-flex no-block align-items-center">
            <h4 class="page-title">Detail Transaksi</h4>
          
        </div>
    </div>
</div>

<div class="container-fluid">
    <!-- ============================================================== -->
    <!-- Start Page Content -->
    <!-- ============================================================== -->
    <div class="row">
        <div class="col-12">
            <div class="card">
               
                    <form 
                    action="{{ route('transactions.edit', [$transactions -> id]) }}"
                     method="get">
                            {{ csrf_field() }}
                        <div class="card-body">

                            <div class="form-group row">
                                    <label for="fname" class="col-sm-3 text-right control-label col-form-label">No Invoice</label>
                                    <div class="col-sm-9">
                                        <input type="text" class="form-control" id="name" placeholder="First Name Here"
                                        name="order_name"
                                        value="{{ $transactions -> invoice_no }}"
                                        readonly>
                                    </div>
                                </div>
                            <div class="form-group row">
                                <label for="fname" class="col-sm-3 text-right control-label col-form-label">Nama Order</label>
                                <div class="col-sm-9">
                                    <input type="text" class="form-control" id="name" placeholder="First Name Here"
                                    name="order_name"
                                    value="{{ $transactions -> order_name }}"
                                    readonly>
                                </div>
                            </div>
                          
                            <div class="form-group row">
                                <label for="cono1" class="col-sm-3 text-right control-label col-form-label">Customer</label>
                                <div class="col-sm-9">
                                    <input type="text" class="form-control" id="price"
                                    name="customer"
                                    value="{{ $customers -> name }}"
                                    readonly>
                                </div>
                            </div>

                            <div class="form-group row">
                                    <label for="cono1" class="col-sm-3 text-right control-label col-form-label">Tanggal Order</label>
                                    <div class="col-sm-9">
                                        <input type="text" class="form-control" id="price"
                                        name="created_at"
                                        value="{{ $transactions -> created_at }}"
                                        readonly>
                                    </div>
                            </div>

                            <div class="form-group row">
                                    <label for="cono1" class="col-sm-3 text-right control-label col-form-label">Tanggal Jadi</label>
                                    <div class="col-sm-9">
                                        <input type="text" class="form-control" id="price"
                                        name="tanggal_jadi"
                                        value="{{ $transactions -> tanggal_jadi }}"
                                        readonly>
                                    </div>
                            </div>

                            <div class="form-group row">
                                    <label for="cono1" class="col-sm-3 text-right control-label col-form-label">Catatan</label>
                                    <div class="col-sm-9">
                                        <input type="text" class="form-control" id="price"
                                        name="notes"
                                        value="{{ $transactions -> notes }}"
                                        readonly>
                                    </div>
                            </div>

                            <div class="form-group row">
                                    <label for="cono1" class="col-sm-3 text-right control-label col-form-label">Status</label>
                                    <div class="col-sm-9">
                                        <input type="text" class="form-control" id="price"
                                        name="notes"
                                        value="{{ $transactions -> status }}"
                                        readonly>
                                    </div>
                            </div>

                            <div class="table-responsive">
                                    <div id="zero_config_wrapper" class="dataTables_wrapper container-fluid dt-bootstrap4">
                                       
                                        <div class="row">
                                            <div class="col-sm-12">
                                                <table  class="table table-striped table-bordered" role="grid"
                                                    aria-describedby="zero_config_info">
                                                    <thead>
                                                        <tr role="row">
                                                            <th class="sorting_asc" tabindex="0" aria-controls="zero_config" rowspan="1"
                                                                colspan="1" aria-sort="ascending" aria-label="Nomor: activate to sort column descending"
                                                                style="width: 10px;">No</th>
                                                            <th class="sorting" tabindex="0" aria-controls="zero_config" rowspan="1"
                                                                colspan="1" aria-label="Nama: activate to sort column ascending" style="width: 80px;">
                                                                Nama Produk</th>
                                                            <th class="sorting" tabindex="0" aria-controls="zero_config" rowspan="1"
                                                                colspan="1" aria-label="Alamat: activate to sort column ascending"
                                                                style="width: 80px;">Harga Satuan</th>
                                                            <th class="sorting" tabindex="0" aria-controls="zero_config" rowspan="1"
                                                                colspan="1" aria-label="No HP: activate to sort column ascending" style="width: 50px;">
                                                                Jumlah</th>
                                                            
                                                            <th class="sorting" tabindex="0" aria-controls="zero_config" rowspan="1"
                                                                colspan="1" aria-label="No HP: activate to sort column ascending" style="width: 50px;">
                                                                Jumlah Harga</th>            
                                                        </tr>
                                                    </thead>
        
                                                    <tbody>
                                                        <?php $urut=0; ?>
                                                      
                                                        @foreach ($products as $product)
                                                        <?php $urut++; ?>
                                                        <tr role="row" class="odd">
                                                            <td class="sorting_1">
                                                                <?php echo $urut; ?>
                                                            </td>
                                                            <td>{{ $product -> name }}</td>
                                                            <td>{{ $product -> price }}</td>
                                                            <td>{{ $product-> pivot-> quantity }}</td>
                                                            <td>{{ $product-> pivot-> jumlah_harga }}</td>
                                                        </tr>
                                                        @endforeach
                                                    </tbody>
                
                                                  
                                            
                                                </table>
        
                                                <div class="form-group row">
                                                    <label for="fname" class="col-sm-3 text-right control-label col-form-label">Total Biaya</label>
                                                    <div class="col-sm-9">
                                                        <input type="text" class="form-control" id="name" placeholder="First Name Here"
                                                        name="total"
                                                        value="{{ $transactions -> total }}"
                                                        readonly>
                                                    </div>
                                                </div>
        
                                                <div class="form-group row">
                                                <label for="fname" class="col-sm-3 text-right control-label col-form-label">Bayar</label>
                                                <div class="col-sm-9">
                                                    <input type="text" class="form-control" id="name" placeholder="First Name Here"
                                                    name="payment"
                                                    value="{{ $transactions -> payment }}"
                                                    readonly>
                                                </div>                                        
                                                </div>
        
                                                <div class="form-group row">
                                                    <label for="fname" class="col-sm-3 text-right control-label col-form-label">Kekurangan</label>
                                                    <div class="col-sm-9">
                                                        <input type="text" class="form-control" id="name" placeholder="First Name Here"
                                                        name="kurang"
                                                        value="{{ $transactions -> kurang }}"
                                                        readonly>
                                                    </div>                                        
                                                    </div>
        
                                            </div>
                                        </div>
                
                                    </div>
                                </div>

                        </div>
                        {{-- <div class="border-top">
                            <div class="card-body">
                                <button type="submit" class="btn btn-primary">Edit</button>
                            </div>
                        </div> --}}
                    </form>               

            </div>

        </div>
    </div>

    

</div>

<script>  
        $(document).ready(function(){  
             var i=1;  
             $('#add').click(function(){  
                  i++;  
                  $('#dynamic_field').append('<tr id="row'+i+'"><td><input type="text" name="name[]" placeholder="Enter your Name" class="form-control name_list" /></td><td><button type="button" name="remove" id="'+i+'" class="btn btn-danger btn_remove">X</button></td></tr>');  
             });  
             $(document).on('click', '.btn_remove', function(){  
                  var button_id = $(this).attr("id");   
                  $('#row'+button_id+'').remove();  
             });  
             $('#submit').click(function(){            
                //   $.ajax({  
                //        url:"name.php",  
                //        method:"POST",  
                //        data:$('#add_name').serialize(),  
                //        success:function(data)  
                //        {  
                //             alert(data);  
                //             $('#add_name')[0].reset();  
                //        }  
                //   });  
             });  
        });  
        </script>

@endsection

resources/views/transactions/index.blade.php
@extends('layouts.root')

@section('content')

<div class="page-breadcrumb">
    <div class="row">
        <div class="col-12 d-flex no-block align-items-center">
            <h4 class="page-title">Data Transaksi</h4>
            <div class="ml-auto text-right">
                <a href="/transactions/create"><button type="button" class="btn btn-success">Tambah Transaksi</button></a>                      
            </div>
        </div>
    </div>
</div>

<div class="container-fluid">
    
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <div class="table-responsive">
                    <div id="zero_config_wrapper" class="dataTables_wrapper container-fluid dt-bootstrap4">
                       
                        <div class="row">
                            <div class="col-sm-12">
                                <table id="zero_config" class="table table-striped table-bordered dataTable" role="grid"
                                    aria-describedby="zero_config_info">
                                    <thead>
                                        <tr role="row">
                                            <th class="sorting_asc" tabindex="0" aria-controls="zero_config" rowspan="1"
                                                colspan="1" aria-sort="ascending" aria-label="Nomor: activate to sort column descending"
                                                style="width: 10px;">No</th>
                                            {{-- <th class="sorting" tabindex="0" aria-controls="zero_config" rowspan="1"
                                                colspan="1" aria-label="Nama: activate to sort column ascending" 
                                                style="width: 80px;">No. Invoice</th> --}}
                                            <th class="sorting" tabindex="0" aria-controls="zero_config" rowspan="1"
                                                colspan="1" aria-label="Alamat: activate to sort column ascending"
                                                style="width: 80px;">Nama Order</th>
                                            <th class="sorting" tabindex="0" aria-controls="zero_config" rowspan="1"
                                                colspan="1" aria-label="No HP: activate to sort column ascending" style="width: 50px;">
                                                Tanggal Order</th>
                                            
                                            <th class="sorting" tabindex="0" aria-controls="zero_config" rowspan="1"
                                                colspan="1" aria-label="No HP: activate to sort column ascending" style="width: 50px;">
                                                Tanggal Jadi</th>
                                            <th class="sorting" tabindex="0" aria-controls="zero_config" rowspan="1"
                                                colspan="1" aria-label="No HP: activate to sort column ascending" style="width: 50px;">
                                                Total</th>
                                            <th class="sorting" tabindex="0" aria-controls="zero_config" rowspan="1"
                                                colspan="1" aria-label="No HP: activate to sort column ascending" style="width: 50px;">
                                                Kurang</th>
                                            <th class="sorting" tabindex="0" aria-controls="zero_config" rowspan="1"
                                                colspan="1" aria-label="No HP: activate to sort column ascending" style="width: 50px;">
                                                Status</th>
                                            <th class="sorting" tabindex="0" aria-controls="zero_config" rowspan="1"
                                                colspan="1" aria-label="Aksi" style="width: 30px;">Aksi</th>
                                        </tr>
                                    </thead>

                                    <tbody>
                                        <?php $urut=0; ?>
                                        @foreach ($transactions as $transaction)
                                        <?php $urut++; ?>
                                        <tr role="row" class="odd">
                                            <td class="sorting_1">
                                                <?php echo $urut; ?>
                                            </td>
                                            {{-- <td>{{ $transaction -> invoice_no }}</td> --}}
                                            <td>{{ $transaction -> order_name }}</td>
                                            <td>{{ $transaction -> created_at }}</td>
                                            <td>{{ $transaction -> tanggal_jadi }}</td>
                                            <td>{{ $transaction -> total_order }}</td>
                                            <td>{{ $transaction -> kurang }}</td>
                                            <td>{{ $transaction -> status }}</td>

                                            <td>
                                                    <ul class="d-flex justify-content-center" style=" list-style-type: none;">
                                                        <li class="mr-3"><a href="/transactions/{{ $transaction -> id }}" ><button type="button" class="btn btn-primary btn-sm">Detail</button></a></li>
                                                            
                                                            {{-- <li class="mr-3"><a href="/transactions/{{ $transaction -> id }}/edit"><button type="button" class="btn btn-info btn-sm">Edit</button></a></li> --}}
                                                            
                                                            <li>
                                                                    <button class="btn btn-danger btn-sm" 
                                                                    data-catid= {{ $transaction-> id}} 
                                                                    data-toggle="modal" 
                                                                    data-target="#delete">Delete</button>
                                                            </li>
                                                           
                                                        </ul>
                                            </td>
                                        </tr>
                                        @endforeach
                                    </tbody>
                              
                                    {{-- <tfoot>
                                        <tr>
                                            <th rowspan="1" colspan="1">Nomor</th>
                                            <th rowspan="1" colspan="1">Nama</th>
                                            <th rowspan="1" colspan="1">Alamat</th>
                                            <th rowspan="1" colspan="1">No. HP</th>
                                            <th rowspan="1" colspan="1">Aksi</th>
                                        </tr>
                                    </tfoot> --}}
                                </table>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>

<!-- Modal -->
<div class="modal modal-danger fade" id="delete" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h4 class="modal-title text-center">Delete Confirmation</h4>
            </div>
            <form 
            action="{{ route( 'transactions.destroy','tes') }}" 
            method="post">
                    {{method_field('delete')}}
                    {{csrf_field()}}
                <div class="modal-body">
                      <p class="text-center">
                          Yakin ingin menghapus data ini?
                      </p>
                        <input type="hidden" name="order_id" id="cat_id" value="">
      
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-success" data-dismiss="modal">Batal</button>
                  <button type="submit" class="btn btn-warning">Hapus</button>
                </div>
            </form>
          </div>
        </div>
      </div>
@endsection