routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/tes', function () {
    return view('layouts.tes');
});

Route::get('/api/products',function(){
	return App\Product::where('name','LIKE','%'.request('q').'%')->paginate(10);
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::middleware(['auth'])->group(function (){

    Route::get('autocomplete', 'ProductsController@autocomplete')->name('autocomplete');
    Route::resource('customers', 'CustomersController');
    Route::resource('products', 'ProductsController');
    Route::resource('reports', 'ReportController');
    Route::resource('transactions', 'TransactionsController');
    Route::resource('costs', 'ProductionCostsController');
    Route::resource('units', 'UnitProductsController');

    Route::get('/findPrice','TransactionsController@findPrice');

    Route::get('/transactionData','ProductionCostsController@transactionData');
    Route::get('/unitPrice','ProductionCostsController@unitPrice');

    Route::get('invoice','TransactionsController@invoice');
    Route::post('/transactions/postInvoice','TransactionsController@postInvoice');
});











Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/UnitProduct.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class UnitProduct extends Model
{

    // protected $table = 'unit_products';

    protected $fillable = [
        'id',
        'name',
        'price'
    ];

    public function Products(){
        return $this->hasMany('App\Product','unit_id');
    }

    public function Costs()
    {
        return $this->belongsToMany('App\ProductionCost','productioncost_unit');
    }
}

app/Http/Controllers/UnitProductsController.php
<?php

namespace App\Http\Controllers;

use App\UnitProduct;
use Illuminate\Support\Facades\DB;
use Illuminate\Http\Request;

class UnitProductsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // $units = DB::table('unit_products')->get();
        $units = UnitProduct::all();

        // dd($units);
        return view('unit_products.index',['units' => $units]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('unit_products.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $units = UnitProduct::create([
            'name' => $request->input('name'),
            'price' => $request->input('price')
        ]);

        if ($units) {
            # code...
            return redirect()->route('units.index')
            ->with('success', 'Unit created successfully');
        }
        return back()->withInput()->with('errors', 'operation failed');

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\UnitProduct  $unitProduct
     * @return \Illuminate\Http\Response
     */
    public function show($unitProduct)
    {
        $units = UnitProduct::find($unitProduct);
        // dd($units);
        // $units = UnitProduct::where('id', $unitProduct-> id);
        // $units = DB::table('unit_products')->where('id',$unitProduct-> id);
        return view('unit_products.show', ['units' => $units]);
       
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\UnitProduct  $unitProduct
     * @return \Illuminate\Http\Response
     */
    public function edit($unitProduct)
    {
        $units = UnitProduct::find($unitProduct);
        return view('unit_products.edit',['units' => $units]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\UnitProduct  $unitProduct
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $unitProduct)
    {
        $unitUpdate = UnitProduct::where('id', $unitProduct)
        ->update([
            'name' => $request->input('name'),
            'price' => $request->input('price'),
        ]);

        if ($unitUpdate) {
            return redirect()->route('units.index')
            ->with('success', 'Update Successfully');
        }
        
        return back()->withInput();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\UnitProduct  $unitProduct
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request)
    {
        $deleteUnit = UnitProduct::find($request-> unit_id);
        if ($deleteUnit->delete()) {
            
            return redirect()->route('units.index')
            ->with('success', 'Unit Produk deleted successfully');
        }

        return back()->withInput()->with('error','operation failed');
    }
}

resources/views/unit_products/create.blade.php
@extends('layouts.root')

@section('content')

<div class="page-breadcrumb">
    <div class="row">
        <div class="col-12 d-flex no-block align-items-center">
            <h4 class="page-title">Tambah Unit Produk</h4>
        </div>
    </div>
</div>

<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <div class="card">
                    <form 
                    action="{{ route('units.store') }}" 
                    method="POST">
                            {{ csrf_field() }}
                        <div class="card-body">
                            <div class="form-group row">
                                <label for="fname" class="col-sm-3 text-right control-label col-form-label">Nama <span class="required">*</span></label>
                                <div class="col-sm-9">
                                    <input type="text" class="form-control" id="name" 
                                    placeholder="Inputkan Nama Unit"
                                    name="name"
                                    required>
                                </div>
                            </div>
                          
                            <div class="form-group row">
                                <label for="cono1" class="col-sm-3 text-right control-label col-form-label">Harga per Kg
                                    <span class="required">*</span></label>
                                <div class="col-sm-9">
                                    <input type="text" class="form-control" id="price"
                                    placeholder="Inputkan Harga"
                                    name="price"
                                    required>
                                </div>
                            </div>
                        </div>
                        <div class="border-top">
                            <div class="card-body">
                                <button type="submit" class="btn btn-primary">Simpan</button>
                            </div>
                        </div>
                    </form>

            </div>
        </div>
    </div>
</div>
@endsection

resources/views/unit_products/edit.blade.php
@extends('layouts.root')

@section('content')

<div class="page-breadcrumb">
    <div class="row">
        <div class="col-12 d-flex no-block align-items-center">
            <h4 class="page-title">Edit Unit Produk</h4>
           
        </div>
    </div>
</div>

<div class="container-fluid">
    
    <div class="row">
        <div class="col-12">
            <div class="card">
                   
                    <form 
                    action="{{ route('units.update',[$units -> id]) }}" 
                    method="POST">
                            {{ csrf_field() }}

                            <input type="hidden" name="_method" value="put">
                        <div class="card-body">
                            <div class="form-group row">
                                <label for="fname" class="col-sm-3 text-right control-label col-form-label">Nama</label>
                                <div class="col-sm-9">
                                    <input type="text" class="form-control" id="name" placeholder="First Name Here"
                                    name="name"
                                    value="{{ $units -> name }}">
                                </div>
                            </div>
                          
                            <div class="form-group row">
                                <label for="cono1" class="col-sm-3 text-right control-label col-form-label">Harga</label>
                                <div class="col-sm-9">
                                    <input type="text" class="form-control" id="price"
                                    name="price"
                                    value="{{ $units -> price }}">
                                </div>
                            </div>
                        </div>
                        <div class="border-top">
                            <div class="card-body">
                                <button type="submit" class="btn btn-primary">Simpan</button>
                            </div>
                        </div>
                    </form>

            </div>
        </div>
    </div>

</div>
    
@endsection

resources/views/unit_products/index.blade.php
@extends('layouts.root')

@section('content')

<div class="page-breadcrumb">
    <div class="row">
        <div class="col-12 d-flex no-block align-items-center">
            <h4 class="page-title">Data Unit Produk</h4>
            <div class="ml-auto text-right">
                <a href="/units/create"><button type="button" class="btn btn-success">Tambah Unit Produk</button></a>                      
            </div>
        </div>
    </div>
</div>

<div class="container-fluid">
    
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <div class="table-responsive">
                    <div id="zero_config_wrapper" class="dataTables_wrapper container-fluid dt-bootstrap4">
                       
                        <div class="row">
                            <div class="col-sm-12">
                                <table id="zero_config" class="table table-striped table-bordered dataTable" role="grid"
                                    aria-describedby="zero_config_info">
                                    <thead>
                                        <tr role="row">
                                            <th class="sorting_asc" tabindex="0" aria-controls="zero_config" rowspan="1"
                                                colspan="1" aria-sort="ascending" aria-label="Nomor: activate to sort column descending"
                                                style="width: 10px;">Nomor</th>
                                            <th class="sorting" tabindex="1" aria-controls="zero_config" rowspan="1"
                                                colspan="1" aria-label="Nama: activate to sort column ascending" style="width: 80px;">Nama</th>
                                            <th class="sorting" tabindex="2" aria-controls="zero_config" rowspan="1"
                                                colspan="1" aria-label="Nama: activate to sort column ascending" style="width: 80px;">Harga per Kg</th>
                                          
                                            <th  tabindex="3" aria-controls="zero_config" rowspan="1"
                                                colspan="1" aria-label="Aksi" style="width: 30px;">Aksi</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php $urut=0; ?>
                                        @foreach ($units as $unit)
                                        <?php $urut++; ?>
                                        <tr role="row" class="odd">
                                            <td class="sorting_1">
                                                <?php echo $urut; ?>
                                            </td>
                                            <td>{{ $unit -> name }}</td>
                                            <td>{{ $unit -> price }}</td>
                                            <td>
                                                    <ul class="d-flex justify-content-center" style=" list-style-type: none;">
                                                        <li class="mr-3"><a href="/units/{{ $unit -> id }}" ><button type="button" class="btn btn-primary btn-sm">Detail</button></a></li>
                                                            
                                                            <li class="mr-3"><a href="/units/{{ $unit -> id }}/edit"><button type="button" class="btn btn-info btn-sm">Edit</button></a></li>
                                                            
                                                            <li>
                                                                    <button class="btn btn-danger btn-sm" 
                                                                    data-catid={{$unit-> id}} 
                                                                    data-toggle="modal" 
                                                                    data-target="#delete">Delete</button>
                                                            </li>
                                                           
                                                        </ul>
                                            </td>
                                        </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>

<!-- Modal -->
<div class="modal modal-danger fade" id="delete" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h4 class="modal-title text-center">Delete Confirmation</h4>
            </div>
            <form action="{{ route( 'units.destroy','tes') }}" method="post">
                    {{method_field('delete')}}
                    {{csrf_field()}}
                <div class="modal-body">
                      <p class="text-center">
                          Yakin ingin menghapus data ini?
                      </p>
                        <input type="hidden" name="unit_id" id="cat_id" value="">
      
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-success" data-dismiss="modal">Batal</button>
                  <button type="submit" class="btn btn-danger">Hapus</button>
                </div>
            </form>
          </div>
        </div>
      </div>
@endsection

resources/views/unit_products/show.blade.php
@extends('layouts.root')

@section('content')

<div class="page-breadcrumb">
    <div class="row">
        <div class="col-12 d-flex no-block align-items-center">
            <h4 class="page-title">Unit Detail</h4>
          
        </div>
    </div>
</div>

<div class="container-fluid">
    <!-- ============================================================== -->
    <!-- Start Page Content -->
    <!-- ============================================================== -->
    <div class="row">
        <div class="col-12">
            <div class="card">
               
                    <form 
                    action="{{ route('units.edit', [$units -> id]) }}"
                     method="get">
                            {{ csrf_field() }}
                        <div class="card-body">
                            <div class="form-group row">
                                <label for="fname" class="col-sm-3 text-right control-label col-form-label">Nama</label>
                                <div class="col-sm-9">
                                    <input type="text" class="form-control" id="name" placeholder="First Name Here"
                                    name="name"
                                    value="{{ $units -> name }}"
                                    readonly>
                                </div>
                            </div>
                          
                            <div class="form-group row">
                                <label for="cono1" class="col-sm-3 text-right control-label col-form-label">Nomor HP</label>
                                <div class="col-sm-9">
                                    <input type="text" class="form-control" id="price"
                                    name="price"
                                    value="{{ $units -> price }}"
                                    readonly>
                                </div>
                            </div>

                        </div>
                        <div class="border-top">
                            <div class="card-body">
                                <button type="submit" class="btn btn-primary">Edit</button>
                            </div>
                        </div>
                    </form>

                  

            </div>
        </div>
    </div>

</div>
    
@endsection